### ISSUE TITLE
AttributeError: 'Web3' object has no attribute 'middleware_stack'

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#1422]
* Version: 5.0.1
* Python: 3.6.3
* OS: linux

Following code was working on `web3==4.9.2`, which does not work for the `web3==5.0.1`. I am getting following error:

```
    web3.middleware_stack.inject(geth_poa_middleware, layer=0)
AttributeError: 'Web3' object has no attribute 'middleware_stack'
```

---------

```
web3 = Web3(IPCProvider('/private/geth.ipc'))
from web3.middleware import geth_poa_middleware
# inject the poa compatibility middleware to the innermost layer
web3.middleware_stack.inject(geth_poa_middleware, layer=0)
from web3.shh import Shh
Shh.attach(web3, 'shh')
```

**Comment by avatar-lavventura** [comment]
[Web3.middleware_onion.add(middleware, name=None)][1]



Replacing `web3.middleware_stack.inject(geth_poa_middleware, layer=0)` with `web3.middleware_onion.inject(geth_poa_middleware, layer=0)` fixed the problem.


  [1]: https://web3py.readthedocs.io/en/stable/middleware.html#Web3.middleware_onion.add
