### ISSUE TITLE
Add python 3.7 to CI tests

### ISSUE THREAD

**Issue by dylanjw** [ethereum/web3.py#968]
### What was wrong?
python 3.7 is out, and we should include it in our testing.

### How can it be fixed?

add python 3.7 to our tox.ini & circleci config

**Comment by veox** [comment]
For ref: https://github.com/ethereum/py-evm/issues/970 - same-topic tracking issue in `py-evm`; with some initial findings - haven't revisited in 2 weeks.

**Comment by voith** [comment]
`python3.7` support in `websockets` was added in `v6.0`.

**Comment by voith** [comment]
In #973, someone has already tested `HTTPProvider` with python3.7 and it seems functional. `websockets` might be the only library that might need a version upgrade.

**Comment by voith** [comment]
I tried testing python3.7 with my fork today, but the build is failing. https://circleci.com/gh/voith/web3.py/3206
Looks like we'll have to wait for `py-evm` to  work with python3.7. Curently, plylevel gives the following error:
```
  plyvel/_plyvel.cpp:547:24: fatal error: leveldb/db.h: No such file or directory
   #include "leveldb/db.h"
                          ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

```
Looking at https://github.com/ethereum/py-evm/pull/1109, it seems like it can fixed by bumping the `plylevel` version.

**Comment by veox** [comment]
`py-evm` should now be good with Python 3.7.

@voith - seems you've already started working on this; could you craft a PR?..

**Comment by voith** [comment]
@veox Thanks for informing. I was waiting for `py-evm`  to be released, so that I can make the corresponding change in `eth-tester` and `web3`

**Comment by voith** [comment]
waiting on https://github.com/ethereum/eth-tester/pull/120

**Comment by voith** [comment]
all blockers removed. #996 should close this issue.
